In [256]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [212]:
df = pd.read_csv('train.csv')

In [213]:
df

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [214]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [215]:
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [216]:
df['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars', nan], dtype=object)

In [217]:
df['HomePlanet'].fillna(3, inplace = True)

In [218]:
df['HomePlanet'][55:65]

55    Earth
56    Earth
57    Earth
58     Mars
59        3
60    Earth
61    Earth
62    Earth
63    Earth
64     Mars
Name: HomePlanet, dtype: object

In [219]:
df['CryoSleep'].unique()

array([False, True, nan], dtype=object)

In [220]:
df['CryoSleep'].fillna(2, inplace = True)

In [221]:
df['CryoSleep'].unique()

array([False, True, 2], dtype=object)

In [222]:
df['CryoSleep'].value_counts()

False    5439
True     3037
2         217
Name: CryoSleep, dtype: int64

In [223]:
df['Cabin'].unique()

array(['B/0/P', 'F/0/S', 'A/0/S', ..., 'G/1499/S', 'G/1500/S', 'E/608/S'],
      dtype=object)

In [224]:
df['VIP'].unique()

array([False, True, nan], dtype=object)

In [225]:
df['VIP'].fillna(2, inplace = True)

In [226]:
df['VIP'].value_counts()

False    8291
2         203
True      199
Name: VIP, dtype: int64

In [227]:
df.drop(['Cabin', 'Destination', 'Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name'], axis=1, inplace=True)

In [228]:
df

PassengerId HomePlanet CryoSleep    VIP  Transported
0        0001_01     Europa     False  False        False
1        0002_01      Earth     False  False         True
2        0003_01     Europa     False   True        False
3        0003_02     Europa     False  False        False
4        0004_01      Earth     False  False         True
...          ...        ...       ...    ...          ...
8688     9276_01     Europa     False   True        False
8689     9278_01      Earth      True  False        False
8690     9279_01      Earth     False  False         True
8691     9280_01     Europa     False  False        False
8692     9280_02     Europa     False  False         True

[8693 rows x 5 columns]

In [229]:
df.shape

(8693, 5)

In [230]:
numerical_columns = ['HomePlanet', 'CryoSleep', 'VIP']
df[numerical_columns] = df[numerical_columns].astype(str)

In [231]:
df[numerical_columns]

HomePlanet CryoSleep    VIP
0        Europa     False  False
1         Earth     False  False
2        Europa     False   True
3        Europa     False  False
4         Earth     False  False
...         ...       ...    ...
8688     Europa     False   True
8689      Earth      True  False
8690      Earth     False  False
8691     Europa     False  False
8692     Europa     False  False

[8693 rows x 3 columns]

In [232]:
le = LabelEncoder()
for col in numerical_columns:
    df[col] = le.fit_transform(df[col])

In [233]:
s = StandardScaler()

In [234]:
s.fit_transform(df)

array([[-1.73441071e+00,  4.51062998e-01, -6.25361379e-01,
         2.13975041e-03, -1.00727366e+00],
       [-1.73403630e+00, -7.57285428e-01, -6.25361379e-01,
         2.13975041e-03,  9.92778861e-01],
       [-1.73366190e+00,  4.51062998e-01, -6.25361379e-01,
         4.65235234e+00, -1.00727366e+00],
       ...,
       [ 1.73935681e+00, -7.57285428e-01, -6.25361379e-01,
         2.13975041e-03,  9.92778861e-01],
       [ 1.73973122e+00,  4.51062998e-01, -6.25361379e-01,
         2.13975041e-03, -1.00727366e+00],
       [ 1.73973496e+00,  4.51062998e-01, -6.25361379e-01,
         2.13975041e-03,  9.92778861e-01]])

In [235]:
X = df.drop('Transported', axis = 1)

In [236]:
X

PassengerId  HomePlanet  CryoSleep  VIP
0        0001_01           2          1    1
1        0002_01           1          1    1
2        0003_01           2          1    2
3        0003_02           2          1    1
4        0004_01           1          1    1
...          ...         ...        ...  ...
8688     9276_01           2          1    2
8689     9278_01           1          2    1
8690     9279_01           1          1    1
8691     9280_01           2          1    1
8692     9280_02           2          1    1

[8693 rows x 4 columns]

In [237]:
X.shape

(8693, 4)

In [238]:
y = df['Transported']

In [239]:
y

0       False
1        True
2       False
3       False
4        True
        ...  
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 8693, dtype: bool

In [200]:
y.shape

(8693,)

In [241]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2 ,random_state=42)

In [250]:
print('X-train shape', X_train.shape, '\n''y-train shape', y_train.shape, '\n''X_test shape', 
      X_test.shape, '\n''y_test shape', y_test.shape)

X-train shape (6954, 4) 
y-train shape (6954,) 
X_test shape (1739, 4) 
y_test shape (1739,)


In [252]:
dc = DecisionTreeClassifier()

In [253]:
dc.fit(X_train, y_train)

DecisionTreeClassifier()

In [254]:
pred = dc.predict(X_test)

In [255]:
pred

array([ True, False,  True, ...,  True,  True,  True])

In [257]:
acc = accuracy_score(y_test,pred)

In [258]:
acc

0.6244968372627947